export const data=[
    {
        id: 1,
        content: "C",
        colorL: "#ECFAF4",
        colorLT: "#7AD6B5",
        colorD: "#313131",
        colorDT: "#D4D4D4",
    },
    {
        id: 2,
        content: "+/-",
        colorL: "#ECFAF4",
        colorLT: "#7AD6B5",
        colorD: "#313131",
        colorDT: "#D4D4D4",
    },
    {
        id: 3,
        content: "%",
        colorL: "#ECFAF4",
        colorLT: "#7AD6B5",
        colorD: "#313131",
        colorDT: "#D4D4D4",
    },
    {
        id: 4,
        content: "÷",
        colorL: "#ECFAF4",
        colorLT: "#7AD6B5",
        colorD: "#313131",
        colorDT: "#D4D4D4",
    },
    {
        id: 5,
        content: "7",
        colorL: "#FAFAFA",
        colorLT: "#000",
        colorD: "#181818",
        colorDT: "#8B898B",
    },
    {
        id: 6,
        content: "8",
        colorL: "#FAFAFA",
        colorLT: "#000",
        colorD: "#181818",
        colorDT: "#8B898B",
    },
    {
        id: 7,
        content: "9",
        colorL: "#FAFAFA",
        colorLT: "#000",
        colorD: "#181818",
        colorDT: "#8B898B",
    },
    {
        id: 8,
        content: "×",
        colorL: "#ECFAF4",
        colorLT: "#7AD6B5",
        colorD: "#313131",
        colorDT: "#E1E1E1",
    },
    {
        id: 9,
        content: "4",
        colorL: "#FAFAFA",
        colorLT: "#000",
        colorD: "#181818",
        colorDT: "#8B898B",
    },
    {
        id: 10,
        content: "5",
        colorL: "#FAFAFA",
        colorLT: "#000",
        colorD: "#181818",
        colorDT: "#8B898B",
    },
    {
        id: 11,
        content: "6",
        colorL: "#FAFAFA",
        colorLT: "#000",
        colorD: "#181818",
        colorDT: "#8B898B",
    },
    {
        id: 12,
        content: "-",
        colorL: "#ECFAF4",
        colorLT: "#7AD6B5",
        colorD: "#313131",
        colorDT: "#E1E1E1",
    },
    {
        id: 13,
        content: "1",
        colorL: "#FAFAFA",
        colorLT: "#000",
        colorD: "#181818",
        colorDT: "#8B898B",
    },
    {
        id: 14,
        content: "2",
        colorL: "#FAFAFA",
        colorLT: "#000",
        colorD: "#181818",
        colorDT: "#8B898B",
    },
    {
        id: 15,
        content: "3",
        colorL: "#FAFAFA",
        colorLT: "#000",
        colorD: "#181818",
        colorDT: "#8B898B",
    },
    {
        id: 16,
        content: "+",
        colorL: "#ECFAF4",
        colorLT: "#7AD6B5",
        colorD: "#313131",
        colorDT: "#E1E1E1",
    },
    {
        id: 17,
        content: "0",
        colorL: "#FAFAFA",
        colorLT: "#000",
        colorD: "#181818",
        colorDT: "#8B898B",
    },
    {
        id: 18,
        content: ".",
        colorL: "#FAFAFA",
        colorLT: "#000",
        colorD: "#181818",
        colorDT: "#8B898B",
    },
    {
        id: 19,
        content: "x²",
        colorL: "#FAFAFA",
        colorLT: "#000",
        colorD: "#181818",
        colorDT: "#8B898B",
    },
    {
        id: 20,
        content: "=",
        colorL: "#F8DADE",
        colorLT: "#E25D6F",
        colorD: "#6D6D6D",
        colorDT: "#C1C1C1",
    },
]